// 24 curated products spread across 5 categories and 5 styles.
// Image URLs are Picsum placeholders for the initial seed; replaced in Phase 9.
const img = (seed) => `https://picsum.photos/seed/${seed}/1600/1100.jpg`;

const catalog = [
  {
    name: "Halden Lounge",
    shortDescription: "A reclined silhouette in saddle leather and walnut.",
    description:
      "Halden takes the mid-century lounge to its quietest expression. The frame is solid walnut, mortise-and-tenoned for stillness; the cushioning is hand-stitched saddle leather over horsehair. Built to settle into for a long evening.\n\nDelivery is white-glove; assembly takes minutes.",
    images: [img("halden-1"), img("halden-2"), img("halden-3"), img("halden-4")],
    category: ["Living room"],
    style: "Mid-century",
    dimensions: { height: 820, width: 760, depth: 880 },
    material: ["Walnut", "Leather"],
    color: "brown",
    price: 1890,
    tags: ["walnut", "leather", "handcrafted"],
    isFeatured: true,
  },
  {
    name: "Marlow Sofa",
    shortDescription: "Three seats of brushed bouclé on an oak plinth.",
    description:
      "Marlow is a long, low sofa designed to anchor a room without filling it. The bouclé is wool-rich and density-tuned; the plinth is white oak with a soft natural oil.\n\nMade to order in eight weeks.",
    images: [img("marlow-1"), img("marlow-2"), img("marlow-3"), img("marlow-4")],
    category: ["Living room"],
    style: "Contemporary",
    dimensions: { height: 720, width: 2400, depth: 950 },
    material: ["Oak", "Bouclé"],
    color: "white",
    price: 3200,
    tags: ["bouclé", "oak", "made-to-order"],
    isFeatured: true,
  },
  {
    name: "Nori Coffee Table",
    shortDescription: "A low slab of charred ash on tapered legs.",
    description:
      "Nori uses shou sugi ban — Japanese charred ash — for its top, sealing the grain in deep matte black. Legs are blackened steel, tapered to almost-nothing.\n\nA piece that disappears underneath the room around it.",
    images: [img("nori-1"), img("nori-2"), img("nori-3")],
    category: ["Living room"],
    style: "Japandi",
    dimensions: { height: 320, width: 1200, depth: 600 },
    material: ["Ash", "Steel"],
    color: "black",
    price: 740,
    tags: ["shou-sugi-ban", "low", "japandi"],
  },
  {
    name: "Atlas Bookshelf",
    shortDescription: "Welded steel shelving with reclaimed oak planks.",
    description:
      "Atlas is industrial in the original sense — built for libraries and workshops. Powder-coated steel uprights, oak planks pulled from decommissioned barns.\n\nFloor-anchored or freestanding; ships flat.",
    images: [img("atlas-1"), img("atlas-2"), img("atlas-3"), img("atlas-4")],
    category: ["Living room", "Home office"],
    style: "Industrial",
    dimensions: { height: 2100, width: 1800, depth: 380 },
    material: ["Steel", "Oak"],
    color: "black",
    price: 1150,
    tags: ["industrial", "modular"],
  },
  {
    name: "Linden Sideboard",
    shortDescription: "Fluted ash doors over a clean ash carcass.",
    description:
      "Linden is a Scandinavian sideboard restrained to its essentials. The fluted door fronts are turned on a horizontal lathe; the carcass is rift-cut ash.\n\nSoft-close hinges; one shelf adjustable.",
    images: [img("linden-1"), img("linden-2"), img("linden-3"), img("linden-4")],
    category: ["Living room", "Dining room"],
    style: "Scandinavian",
    dimensions: { height: 820, width: 1800, depth: 460 },
    material: ["Ash"],
    color: "white",
    price: 2400,
    tags: ["fluted", "ash", "scandinavian"],
    isFeatured: true,
  },
  {
    name: "Saga Bed",
    shortDescription: "A platform bed in white-oiled oak; no headboard.",
    description:
      "Saga is a low platform — Scandinavian in posture, intentionally without a headboard so the wall behind it can do the work. White-oiled oak frame; slatted base.\n\nKing or queen.",
    images: [img("saga-1"), img("saga-2"), img("saga-3"), img("saga-4")],
    category: ["Bedroom"],
    style: "Scandinavian",
    dimensions: { height: 280, width: 1900, depth: 2150 },
    material: ["Oak"],
    color: "white",
    price: 2180,
    tags: ["platform", "oak", "low"],
    isFeatured: true,
  },
  {
    name: "Kelda Nightstand",
    shortDescription: "A single drawer, paper-cord pull, ash carcass.",
    description:
      "Kelda is small. One drawer, one woven paper-cord pull, one open shelf below for a book. Made the same way for sixty years.",
    images: [img("kelda-1"), img("kelda-2"), img("kelda-3")],
    category: ["Bedroom"],
    style: "Japandi",
    dimensions: { height: 520, width: 420, depth: 380 },
    material: ["Ash", "Paper cord"],
    color: "white",
    price: 480,
    tags: ["small", "paper-cord", "ash"],
  },
  {
    name: "Aalto Wardrobe",
    shortDescription: "A pivoting four-door wardrobe in figured walnut.",
    description:
      "Aalto is mid-century at scale. Four pivoting doors in book-matched walnut, brushed-brass spine pulls, internal cedar lining. Hung-rail and shelves on the inside.\n\nFreestanding; not for wall mounting.",
    images: [img("aalto-1"), img("aalto-2"), img("aalto-3"), img("aalto-4")],
    category: ["Bedroom"],
    style: "Mid-century",
    dimensions: { height: 2100, width: 2000, depth: 580 },
    material: ["Walnut", "Cedar", "Brass"],
    color: "brown",
    price: 2950,
    tags: ["walnut", "wardrobe", "freestanding"],
  },
  {
    name: "Vesta Dresser",
    shortDescription: "Six drawers, soft-close, in matte plaster lacquer.",
    description:
      "Vesta is contemporary minimalism in a six-drawer. Front faces are sprayed in matte plaster lacquer over MDF; the carcass is birch ply. Soft-close runners.",
    images: [img("vesta-1"), img("vesta-2"), img("vesta-3")],
    category: ["Bedroom"],
    style: "Contemporary",
    dimensions: { height: 820, width: 1700, depth: 480 },
    material: ["Birch", "Plaster lacquer"],
    color: "white",
    price: 1640,
    tags: ["matte", "minimal"],
  },
  {
    name: "Mira Vanity",
    shortDescription: "A floating vanity with a brushed-brass mirror.",
    description:
      "Mira is wall-mounted; the top floats over open storage. Mirror is round, brushed-brass framed. Drawer fronts are oak veneer.",
    images: [img("mira-1"), img("mira-2"), img("mira-3"), img("mira-4")],
    category: ["Bedroom"],
    style: "Contemporary",
    dimensions: { height: 1500, width: 1100, depth: 420 },
    material: ["Oak", "Brass"],
    color: "brown",
    price: 1090,
    tags: ["mirror", "wall-mounted"],
  },
  {
    name: "Forge Dining Table",
    shortDescription: "A 12-seat dining slab on welded steel trestles.",
    description:
      "Forge is built for long dinners. A single live-edge slab of European oak, finished in matte oil; trestles are blackened welded steel.\n\nShipped flat; trestles bolt on with a single tool.",
    images: [img("forge-1"), img("forge-2"), img("forge-3"), img("forge-4")],
    category: ["Dining room"],
    style: "Industrial",
    dimensions: { height: 760, width: 3200, depth: 1100 },
    material: ["Oak", "Steel"],
    color: "brown",
    price: 2650,
    tags: ["live-edge", "industrial", "12-seat"],
    isFeatured: true,
  },
  {
    name: "Oslo Dining Chair",
    shortDescription: "A bentwood frame and woven paper-cord seat.",
    description:
      "Oslo follows the Scandinavian dining-chair tradition exactly: steam-bent oak frame, woven paper-cord seat, stretchers. Made to last decades.",
    images: [img("oslo-1"), img("oslo-2"), img("oslo-3")],
    category: ["Dining room"],
    style: "Scandinavian",
    dimensions: { height: 780, width: 460, depth: 480 },
    material: ["Oak", "Paper cord"],
    color: "brown",
    price: 320,
    tags: ["bentwood", "paper-cord"],
  },
  {
    name: "Rye Bench",
    shortDescription: "A hardwood dining bench with a tapered profile.",
    description:
      "Rye seats three or four. Solid hardwood plank, hand-shaped tapers, indoor-outdoor finish. Pairs with Forge.",
    images: [img("rye-1"), img("rye-2"), img("rye-3")],
    category: ["Dining room", "Outdoor"],
    style: "Mid-century",
    dimensions: { height: 460, width: 1800, depth: 350 },
    material: ["Hardwood"],
    color: "brown",
    price: 580,
    tags: ["bench", "indoor-outdoor"],
  },
  {
    name: "Larch Buffet",
    shortDescription: "A long buffet with sliding lattice doors.",
    description:
      "Larch slides — instead of swinging — its doors. The fronts are a hand-mortised lattice; behind them, two adjustable shelves.",
    images: [img("larch-1"), img("larch-2"), img("larch-3"), img("larch-4")],
    category: ["Dining room"],
    style: "Japandi",
    dimensions: { height: 820, width: 2100, depth: 460 },
    material: ["Larch"],
    color: "brown",
    price: 1820,
    tags: ["lattice", "japandi"],
  },
  {
    name: "Tide Pendant Light",
    shortDescription: "A blown-glass pendant in seafoam green.",
    description:
      "Tide is hand-blown borosilicate glass, suspended on a brass cord. Sized for a dining table or an entryway. E26 socket; bulb sold separately.",
    images: [img("tide-1"), img("tide-2"), img("tide-3")],
    category: ["Dining room", "Living room"],
    style: "Contemporary",
    dimensions: { height: 320, width: 280, depth: 280 },
    material: ["Glass", "Brass"],
    color: "green",
    price: 410,
    tags: ["pendant", "hand-blown"],
  },
  {
    name: "Ridge Desk",
    shortDescription: "A two-pedestal desk in steel and reclaimed oak.",
    description:
      "Ridge is a workhorse: 1800mm of work surface, two pedestal cabinets with file-rated drawers, cable management trough behind the top.\n\nLeft- or right-handed cable cutout.",
    images: [img("ridge-1"), img("ridge-2"), img("ridge-3"), img("ridge-4")],
    category: ["Home office"],
    style: "Industrial",
    dimensions: { height: 740, width: 1800, depth: 720 },
    material: ["Oak", "Steel"],
    color: "brown",
    price: 1290,
    tags: ["desk", "industrial", "cable-management"],
    isFeatured: true,
  },
  {
    name: "Field Task Chair",
    shortDescription: "An ergonomic task chair in wool-felt and aluminum.",
    description:
      "Field replaces mesh with high-density wool felt, layered over a five-axis ergonomic frame. Aluminum base, forward-tilt mechanism.",
    images: [img("field-1"), img("field-2"), img("field-3")],
    category: ["Home office"],
    style: "Contemporary",
    dimensions: { height: 1100, width: 660, depth: 660 },
    material: ["Wool felt", "Aluminum"],
    color: "grey",
    price: 690,
    tags: ["ergonomic", "wool-felt"],
  },
  {
    name: "Quill Shelving",
    shortDescription: "A modular wall-mount shelving system in walnut.",
    description:
      "Quill is wall-mounted via a continuous rail and brass support pegs. Shelves come in three depths; mix and stack at any height.",
    images: [img("quill-1"), img("quill-2"), img("quill-3"), img("quill-4")],
    category: ["Home office"],
    style: "Mid-century",
    dimensions: { height: 1800, width: 1500, depth: 280 },
    material: ["Walnut", "Brass"],
    color: "brown",
    price: 980,
    tags: ["modular", "wall-mounted"],
  },
  {
    name: "Loam Filing Cabinet",
    shortDescription: "Two-drawer file cabinet in clay-tone enamel.",
    description:
      "Loam is industrial archive-grade in domestic colorways. Two file-rated drawers, baked enamel in clay; brass bail pulls.",
    images: [img("loam-1"), img("loam-2"), img("loam-3")],
    category: ["Home office"],
    style: "Industrial",
    dimensions: { height: 720, width: 460, depth: 600 },
    material: ["Steel", "Brass"],
    color: "orange",
    price: 540,
    tags: ["filing", "enamel"],
  },
  {
    name: "Clay Reading Lamp",
    shortDescription: "A ceramic floor lamp with a paper drum shade.",
    description:
      "Clay's body is wheel-thrown stoneware in unglazed terracotta; the shade is hand-rolled paper. E14 socket; reaches 1.5m.",
    images: [img("clay-1"), img("clay-2"), img("clay-3"), img("clay-4")],
    category: ["Home office", "Living room"],
    style: "Japandi",
    dimensions: { height: 1500, width: 380, depth: 380 },
    material: ["Stoneware", "Paper"],
    color: "orange",
    price: 280,
    tags: ["lamp", "ceramic", "japandi"],
  },
  {
    name: "Coast Lounge Chair",
    shortDescription: "An outdoor lounge in teak and quick-dry sling.",
    description:
      "Coast is built for terraces. Teak, finished bare for natural patina; quick-dry sling fabric in cement grey. Stainless-steel hardware.",
    images: [img("coast-1"), img("coast-2"), img("coast-3"), img("coast-4")],
    category: ["Outdoor"],
    style: "Contemporary",
    dimensions: { height: 880, width: 720, depth: 920 },
    material: ["Teak", "Sling"],
    color: "grey",
    price: 870,
    tags: ["outdoor", "teak"],
  },
  {
    name: "Anvil Fire Table",
    shortDescription: "A patinated steel fire table on iron legs.",
    description:
      "Anvil is a propane fire pit doubled as a low table. Patinated cor-ten steel top, lava rocks included, hidden gas line, 50,000 BTU burner.",
    images: [img("anvil-1"), img("anvil-2"), img("anvil-3"), img("anvil-4")],
    category: ["Outdoor"],
    style: "Industrial",
    dimensions: { height: 380, width: 1100, depth: 1100 },
    material: ["Cor-ten steel", "Iron"],
    color: "brown",
    price: 1460,
    tags: ["fire-pit", "outdoor"],
  },
  {
    name: "Drift Dining Set",
    shortDescription: "Outdoor dining table plus four chairs in white oak.",
    description:
      "Drift is a complete dining set engineered for the outdoors: one 1800mm table plus four armchairs, all in marine-grade white oak with weather-rated joinery.",
    images: [img("drift-1"), img("drift-2"), img("drift-3"), img("drift-4")],
    category: ["Outdoor"],
    style: "Scandinavian",
    dimensions: { height: 760, width: 1800, depth: 900 },
    material: ["White oak"],
    color: "white",
    price: 2200,
    tags: ["outdoor", "dining-set"],
  },
  {
    name: "Bramble Planter Bench",
    shortDescription: "A garden bench with a planter inset on each end.",
    description:
      "Bramble integrates two cedar planters into a bench's profile, so the seat is enclosed by greenery. Recommended for sun-bright entryways.",
    images: [img("bramble-1"), img("bramble-2"), img("bramble-3")],
    category: ["Outdoor"],
    style: "Japandi",
    dimensions: { height: 460, width: 1800, depth: 460 },
    material: ["Cedar"],
    color: "brown",
    price: 390,
    tags: ["planter", "garden"],
  },
];

module.exports = catalog;
